name: 24/7 YouTube Stream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg -y

    - name: Download Video
      run: |
        wget -O video.mp4 "https://drive.google.com/file/d/1iUYqlny9q-KyAeyaiNPgCxDgUshA_72E/view?usp=sharing"

    - name: Start Stream
      run: |
        ffmpeg -re -stream_loop -1 -i video.mp4 \
        -c:v libx264 -preset veryfast -b:v 2500k \
        -c:a aac -b:a 128k \
        -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
