name: 24/7 YT

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg -y

    - name: Start Stream
      run: |
        ffmpeg -re -stream_loop -1 -i Om_Mani_Padme_Hum_Meditating_Spiritual.mp4 \
        -c:v libx264 -preset veryfast -maxrate 3000k -bufsize 6000k \
        -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 \
        -f flv rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}
